# Generated by Django 2.2.28 on 2023-12-07 21:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, unique_for_date='posted', verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Полное содержание')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 0, 46, 51, 952816), verbose_name='Опубликовано')),
                ('image', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'db_table': 'Posts',
                'ordering': ['-posted'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя клиента')),
                ('number', models.CharField(default='+7', max_length=12, unique=True, verbose_name='Номер телефона для связи')),
                ('notice', models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных')),
                ('status', models.CharField(choices=[('1', 'В очереди'), ('2', 'Отменена'), ('3', 'Закрыта')], default='В очереди', max_length=10, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонок',
                'db_table': 'Zayavka',
            },
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за приём')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Список услуг',
                'db_table': 'Uslugi',
            },
        ),
        migrations.CreateModel(
            name='Priem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 0, 46, 51, 959810), verbose_name='Дата приёма')),
                ('number_k', models.CharField(default='+7', max_length=12, unique=True, verbose_name='Номер телефона для связи')),
                ('status', models.CharField(choices=[('1', 'Выполнен'), ('2', 'Отменён'), ('3', 'Запись подтверждена')], default='----', max_length=10, verbose_name='Статус заявки')),
                ('name_k', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='zayavka_name_k', to='app.Zayavka', to_field='name', verbose_name='Ф.И.О.')),
                ('usluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usluga', verbose_name='Наименование услуги')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
                'db_table': 'Priems',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 0, 46, 51, 953816), verbose_name='Дата комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Blog', verbose_name='Статья комментария')),
            ],
            options={
                'verbose_name': 'Комментарии к статье блога',
                'verbose_name_plural': 'Комментарии к статьям блога',
                'db_table': 'Comment',
                'ordering': ['-date'],
            },
        ),
    ]
