# Generated by Django 2.2.28 on 2023-12-09 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231209_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 19, 32, 31, 91223), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 19, 32, 31, 96219), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='name_k',
            field=models.CharField(max_length=100, verbose_name='Ф.И.О. клиента'),
        ),
    ]
