# Generated by Django 2.2.28 on 2023-12-04 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20231204_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uslugi',
            options={'ordering': ['-name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 4, 16, 27, 15, 26156), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 4, 16, 27, 15, 26156), verbose_name='Дата комментария'),
        ),
        migrations.AlterIndexTogether(
            name='uslugi',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='uslugi',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
