# Generated by Django 2.2.28 on 2023-12-04 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20231204_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uslugi',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 4, 16, 44, 0, 84075), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 4, 16, 44, 0, 85074), verbose_name='Дата комментария'),
        ),
    ]
