# Generated by Django 2.2.28 on 2023-12-04 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20231204_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uslugi',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 4, 16, 46, 6, 543788), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 4, 16, 46, 6, 543788), verbose_name='Дата комментария'),
        ),
    ]
