# Generated by Django 2.2.28 on 2023-12-05 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20231204_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 5, 18, 28, 4, 500733), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 5, 18, 28, 4, 501729), verbose_name='Дата комментария'),
        ),
        migrations.CreateModel(
            name='Priem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 5, 18, 28, 4, 504731), verbose_name='Дата приёма')),
                ('name', models.CharField(max_length=12, verbose_name='Номер телефона для связи')),
                ('usluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usluga', verbose_name='Наименование услуги')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
                'db_table': 'Priem',
            },
        ),
    ]
