# Generated by Django 2.2.28 on 2023-12-05 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20231205_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='priem',
            name='number',
            field=models.CharField(default='+7()99-99-999', max_length=12, verbose_name='Номер телефона для связи'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 5, 18, 51, 4, 462582), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 5, 18, 51, 4, 463582), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 5, 18, 51, 4, 465580), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Имя клиента'),
        ),
    ]
