# Generated by Django 2.2.28 on 2023-12-06 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20231205_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'В очереди'), ('2', 'Отменена'), ('3', 'Закрыта')], max_length=1, verbose_name='Статус заявки')),
            ],
        ),
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('number', models.CharField(default='+7', max_length=12, verbose_name='Номер телефона для связи')),
                ('status', models.CharField(default='В очереди', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 3, 14, 239608), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 3, 14, 240608), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 3, 14, 242606), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='number',
            field=models.CharField(default='+7', max_length=12, verbose_name='Номер телефона для связи'),
        ),
    ]
