# Generated by Django 2.2.28 on 2023-12-06 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20231206_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavka',
            options={'verbose_name': 'Заявка на звонок', 'verbose_name_plural': 'Заявки на звонок'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 10, 14, 233482), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 10, 14, 235475), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 10, 14, 241471), verbose_name='Дата приёма'),
        ),
        migrations.AlterModelTable(
            name='zayavka',
            table='Zayavka',
        ),
    ]
