# Generated by Django 2.2.28 on 2023-12-06 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20231206_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 18, 54, 648231), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 18, 54, 649230), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 18, 54, 651229), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='status',
            field=models.CharField(choices=[('1', 'В очереди'), ('2', 'Отменена'), ('3', 'Закрыта')], default='В очереди', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
