# Generated by Django 2.2.28 on 2023-12-06 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20231206_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='notice',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 35, 19, 128110), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 35, 19, 129108), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 6, 12, 35, 19, 131107), verbose_name='Дата приёма'),
        ),
    ]
