# Generated by Django 2.2.28 on 2023-12-07 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20231206_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='priem',
            name='number',
        ),
        migrations.AddField(
            model_name='priem',
            name='name_k',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='zayavka_name_k', to='app.Zayavka', to_field='name', verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='priem',
            name='number_k',
            field=models.ForeignKey(default='+7', on_delete=django.db.models.deletion.CASCADE, related_name='zayavka_number_k', to='app.Zayavka', to_field='number', verbose_name='Номер телефона для связи'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 15, 37, 38, 625420), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 15, 37, 38, 627418), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 15, 37, 38, 632416), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='number',
            field=models.CharField(default='+7', max_length=12, unique=True, verbose_name='Номер телефона для связи'),
        ),
    ]
