# Generated by Django 2.2.28 on 2023-12-07 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20231207_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 15, 45, 56, 512128), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 15, 45, 56, 512128), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 15, 45, 56, 515127), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='number_k',
            field=models.CharField(default='+7', max_length=12, unique=True, verbose_name='Номер телефона для связи'),
        ),
    ]
