# Generated by Django 2.2.28 on 2023-12-07 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20231207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 49, 4, 640196), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 49, 4, 641195), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 49, 4, 644193), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='number_k',
            field=models.ForeignKey(blank=True, default='+7', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Zayavka', verbose_name='Номер телефона для связи'),
        ),
    ]
