# Generated by Django 2.2.28 on 2023-12-07 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20231207_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 55, 6, 12956), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 55, 6, 13955), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 55, 6, 16953), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='number_k',
            field=models.ForeignKey(default='+7', on_delete=django.db.models.deletion.CASCADE, related_name='zayavka_number_k', to='app.Zayavka', to_field='number', verbose_name='Номер телефона для связи'),
        ),
    ]
