# Generated by Django 2.2.28 on 2023-12-07 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20231207_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 58, 1, 389962), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 58, 1, 390962), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 58, 1, 393960), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='number_k',
            field=models.CharField(default='+7', max_length=12, unique=True, verbose_name='Номер телефона для связи'),
        ),
    ]
