# Generated by Django 2.2.28 on 2023-12-07 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20231207_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priem',
            old_name='name_k',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 59, 10, 811231), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 59, 10, 812250), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 19, 59, 10, 815232), verbose_name='Дата приёма'),
        ),
    ]
