# Generated by Django 2.2.28 on 2023-12-07 17:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20231207_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 20, 11, 25, 473191), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 20, 11, 25, 474192), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 20, 11, 25, 477190), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='name',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='zayavka_name_k', to='app.Zayavka', to_field='name', verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя клиента'),
        ),
    ]
