# Generated by Django 2.2.28 on 2023-12-07 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20231207_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='priem',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнен'), ('2', 'Отменён')], default='----', max_length=10, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 22, 7, 33, 281255), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 22, 7, 33, 282254), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 22, 7, 33, 285252), verbose_name='Дата приёма'),
        ),
        migrations.AlterModelTable(
            name='priem',
            table='Priems',
        ),
    ]
