# Generated by Django 2.2.28 on 2023-12-07 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20231207_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priem',
            old_name='name',
            new_name='name_k',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 22, 50, 53, 35762), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 22, 50, 53, 36762), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 22, 50, 53, 39756), verbose_name='Дата приёма'),
        ),
    ]
