# Generated by Django 2.2.28 on 2023-12-07 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20231207_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 23, 15, 19, 822618), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 23, 15, 19, 823617), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 23, 15, 19, 826615), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='name_k',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='zayavka_name_k', to='app.Zayavka', to_field='name', verbose_name='Ф.И.О.'),
        ),
    ]
