# Generated by Django 2.2.28 on 2023-12-07 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20231207_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 23, 41, 41, 747170), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 23, 41, 41, 748163), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 23, 41, 41, 750182), verbose_name='Дата приёма'),
        ),
    ]
