# Generated by Django 2.2.28 on 2023-12-07 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20231208_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 0, 26, 7, 388443), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 0, 26, 7, 389442), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 0, 26, 7, 392440), verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнен'), ('2', 'Отменён'), ('3', 'Запись подтверждена')], default='----', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
